"""create training jobs table

Revision ID: 0124b722b3b9
Revises: 5a082200dd13
Create Date: 2026-06-20 10:59:36.503970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0124b722b3b9'
down_revision: Union[str, Sequence[str], None] = '5a082200dd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('base_model', sa.String(length=255), nullable=False),
    sa.Column('training_type', sa.String(length=100), nullable=False),
    sa.Column(
        'status',
        sa.String(length=50),
        server_default=sa.text("'pending'"),
        nullable=False
    ),
    sa.Column('artifact_path', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='fk_training_job_dataset_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_jobs_dataset_id'), 'training_jobs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_training_jobs_id'), 'training_jobs', ['id'], unique=False)
    op.create_index(
        'ix_training_jobs_status',
        'training_jobs',
        ['status'],
        unique=False
)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_training_jobs_id'), table_name='training_jobs')
    op.drop_index(op.f('ix_training_jobs_dataset_id'), table_name='training_jobs')
    op.drop_table('training_jobs')
    op.drop_index(
        'ix_training_jobs_status',
        table_name='training_jobs'
    )
    # ### end Alembic commands ###
