"""add document security

Revision ID: 114613036eef
Revises: 81d3669af8ae
Create Date: 2026-05-12 05:05:40.973195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '114613036eef'
down_revision: Union[str, Sequence[str], None] = '81d3669af8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('department', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('access_level', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('uploaded_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'uploaded_by')
    op.drop_column('documents', 'access_level')
    op.drop_column('documents', 'department')
    # ### end Alembic commands ###
