"""add plans tables

Revision ID: 134f0d0dac8f
Revises: a372e9782eea
Create Date: 2026-06-11 11:18:40.692321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134f0d0dac8f'
down_revision: Union[str, Sequence[str], None] = 'a372e9782eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_plan_code'), 'plans', ['plan_code'], unique=True)
    op.create_table('plan_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('monthly_token_limit', sa.BigInteger(), nullable=False),
    sa.Column('monthly_request_limit', sa.BigInteger(), nullable=False),
    sa.Column('monthly_cost_limit', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'version_number', name='uq_plan_version')
    )
    op.create_index(op.f('ix_plan_versions_id'), 'plan_versions', ['id'], unique=False)
    op.create_index(op.f('ix_plan_versions_plan_id'), 'plan_versions', ['plan_id'], unique=False)
    op.create_table('plan_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_version_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_price_id', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_version_id', 'provider', 'currency', 'billing_cycle', name='uq_plan_price')
    )
    op.create_index(op.f('ix_plan_prices_id'), 'plan_prices', ['id'], unique=False)
    op.create_index(op.f('ix_plan_prices_plan_version_id'), 'plan_prices', ['plan_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_prices_plan_version_id'), table_name='plan_prices')
    op.drop_index(op.f('ix_plan_prices_id'), table_name='plan_prices')
    op.drop_table('plan_prices')
    op.drop_index(op.f('ix_plan_versions_plan_id'), table_name='plan_versions')
    op.drop_index(op.f('ix_plan_versions_id'), table_name='plan_versions')
    op.drop_table('plan_versions')
    op.drop_index(op.f('ix_plans_plan_code'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
