"""add pipeline execution artifact lineage

Revision ID: 243a01813e73
Revises: cfd60796c9b0
Create Date: 2026-07-04 06:58:21.552404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '243a01813e73'
down_revision: Union[str, Sequence[str], None] = 'cfd60796c9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_execution_artifacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('producer_step_run_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('corpus_source_id', sa.Integer(), nullable=True),
    sa.Column('artifact_code', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('storage_provider', sa.String(length=100), nullable=False),
    sa.Column('storage_reference', sa.String(length=2000), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_source_id'], ['corpus_sources.id'], name='fk_pipeline_execution_artifact_corpus_source_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='fk_pipeline_execution_artifact_dataset_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name='fk_pipeline_execution_artifact_run_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producer_step_run_id'], ['pipeline_step_runs.id'], name='fk_pipeline_execution_artifact_producer_step_run_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id', 'artifact_code', name='uq_pipeline_execution_artifact_code')
    )
    op.create_index(op.f('ix_pipeline_execution_artifacts_artifact_code'), 'pipeline_execution_artifacts', ['artifact_code'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifacts_artifact_type'), 'pipeline_execution_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifacts_checksum'), 'pipeline_execution_artifacts', ['checksum'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifacts_corpus_source_id'), 'pipeline_execution_artifacts', ['corpus_source_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifacts_dataset_id'), 'pipeline_execution_artifacts', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifacts_pipeline_run_id'), 'pipeline_execution_artifacts', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifacts_producer_step_run_id'), 'pipeline_execution_artifacts', ['producer_step_run_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifacts_status'), 'pipeline_execution_artifacts', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifacts_storage_provider'), 'pipeline_execution_artifacts', ['storage_provider'], unique=False)
    op.create_table('pipeline_execution_artifact_edges',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('child_artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_artifact_id'], ['pipeline_execution_artifacts.id'], name='fk_pipeline_artifact_edge_child_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_artifact_id'], ['pipeline_execution_artifacts.id'], name='fk_pipeline_artifact_edge_parent_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_artifact_id', 'child_artifact_id', 'relation_type', name='uq_pipeline_execution_artifact_edge')
    )
    op.create_index(op.f('ix_pipeline_execution_artifact_edges_child_artifact_id'), 'pipeline_execution_artifact_edges', ['child_artifact_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifact_edges_parent_artifact_id'), 'pipeline_execution_artifact_edges', ['parent_artifact_id'], unique=False)
    op.create_index(op.f('ix_pipeline_execution_artifact_edges_relation_type'), 'pipeline_execution_artifact_edges', ['relation_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_execution_artifact_edges_relation_type'), table_name='pipeline_execution_artifact_edges')
    op.drop_index(op.f('ix_pipeline_execution_artifact_edges_parent_artifact_id'), table_name='pipeline_execution_artifact_edges')
    op.drop_index(op.f('ix_pipeline_execution_artifact_edges_child_artifact_id'), table_name='pipeline_execution_artifact_edges')
    op.drop_table('pipeline_execution_artifact_edges')
    op.drop_index(op.f('ix_pipeline_execution_artifacts_storage_provider'), table_name='pipeline_execution_artifacts')
    op.drop_index(op.f('ix_pipeline_execution_artifacts_status'), table_name='pipeline_execution_artifacts')
    op.drop_index(op.f('ix_pipeline_execution_artifacts_producer_step_run_id'), table_name='pipeline_execution_artifacts')
    op.drop_index(op.f('ix_pipeline_execution_artifacts_pipeline_run_id'), table_name='pipeline_execution_artifacts')
    op.drop_index(op.f('ix_pipeline_execution_artifacts_dataset_id'), table_name='pipeline_execution_artifacts')
    op.drop_index(op.f('ix_pipeline_execution_artifacts_corpus_source_id'), table_name='pipeline_execution_artifacts')
    op.drop_index(op.f('ix_pipeline_execution_artifacts_checksum'), table_name='pipeline_execution_artifacts')
    op.drop_index(op.f('ix_pipeline_execution_artifacts_artifact_type'), table_name='pipeline_execution_artifacts')
    op.drop_index(op.f('ix_pipeline_execution_artifacts_artifact_code'), table_name='pipeline_execution_artifacts')
    op.drop_table('pipeline_execution_artifacts')
    # ### end Alembic commands ###
