"""enhance payments table

Revision ID: 25e963c28332
Revises: 86e350de9a4a
Create Date: 2026-06-12 10:00:18.222456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25e963c28332'
down_revision: Union[str, Sequence[str], None] = '86e350de9a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.drop_index(
        'ix_token_usage_id',
        table_name='token_usage'
    )

    op.drop_table(
        'token_usage'
    )

    op.add_column(
        'payments',
        sa.Column(
            'payment_reference',
            sa.String(length=100),
            nullable=True
        )
    )

    op.add_column(
        'payments',
        sa.Column(
            'payment_method',
            sa.String(length=100),
            nullable=True
        )
    )

    op.add_column(
        'payments',
        sa.Column(
            'failure_reason',
            sa.String(length=500),
            nullable=True
        )
    )

    op.add_column(
        'payments',
        sa.Column(
            'idempotency_key',
            sa.String(length=255),
            nullable=True
        )
    )

    op.add_column(
        'payments',
        sa.Column(
            'processed_at',
            sa.DateTime(),
            nullable=True
        )
    )

    # Populate existing rows
    op.execute("""
        UPDATE payments
        SET payment_reference = 'PAY-' || id
        WHERE payment_reference IS NULL
    """)

    # Make NOT NULL after population
    op.alter_column(
        'payments',
        'payment_reference',
        nullable=False
    )

    op.create_index(
        op.f('ix_payments_idempotency_key'),
        'payments',
        ['idempotency_key'],
        unique=True
    )

    op.create_index(
        op.f('ix_payments_payment_reference'),
        'payments',
        ['payment_reference'],
        unique=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_payment_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_column('payments', 'processed_at')
    op.drop_column('payments', 'idempotency_key')
    op.drop_column('payments', 'failure_reason')
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'payment_reference')
    op.create_table('token_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tokens', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='token_usage_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='token_usage_pkey')
    )
    op.create_index('ix_token_usage_id', 'token_usage', ['id'], unique=False)
    # ### end Alembic commands ###
