"""wallet production billing fields

Revision ID: 27825b1c7022
Revises: dce79302ae29
Create Date: 2026-06-09 05:52:42.053383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27825b1c7022'
down_revision: Union[str, Sequence[str], None] = 'dce79302ae29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('wallet_transactions', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('wallet_transactions', sa.Column('balance_before', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('wallet_transactions', sa.Column('balance_after', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('wallet_transactions', sa.Column('reference_type', sa.String(length=50), nullable=True))
    op.add_column('wallet_transactions', sa.Column('reference_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'wallet_transactions', 'users', ['user_id'], ['id'])
    op.add_column('wallets', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('wallets', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('wallets', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('wallets', 'balance',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallets', 'balance',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('wallets', 'updated_at')
    op.drop_column('wallets', 'status')
    op.drop_column('wallets', 'currency')
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.drop_column('wallet_transactions', 'reference_id')
    op.drop_column('wallet_transactions', 'reference_type')
    op.drop_column('wallet_transactions', 'balance_after')
    op.drop_column('wallet_transactions', 'balance_before')
    op.drop_column('wallet_transactions', 'status')
    op.drop_column('wallet_transactions', 'user_id')
    # ### end Alembic commands ###
