"""create model promotions table

Revision ID: 2c5b12e13a6f
Revises: f7e5658a3e24
Create Date: 2026-06-20 12:33:21.728208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2c5b12e13a6f'
down_revision: Union[str, Sequence[str], None] = 'f7e5658a3e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_job_id', sa.Integer(), nullable=False),
    sa.Column(
        'promotion_status',
        sa.String(length=50),
        server_default=sa.text("'pending'"),
        nullable=False
    ),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approval_reason', sa.Text(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),

    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.ForeignKeyConstraint(['evaluation_job_id'], ['evaluation_jobs.id'], name='fk_model_promotion_evaluation_job_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_promotions_evaluation_job_id'), 'model_promotions', ['evaluation_job_id'], unique=False)
    op.create_index(op.f('ix_model_promotions_id'), 'model_promotions', ['id'], unique=False)

    op.create_index(
        'ix_model_promotions_status',
        'model_promotions',
        ['promotion_status'],
        unique=False
    )
   
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        'ix_model_promotions_status',
        table_name='model_promotions'
    )
   
   
    op.drop_index(op.f('ix_model_promotions_id'), table_name='model_promotions')
    op.drop_index(op.f('ix_model_promotions_evaluation_job_id'), table_name='model_promotions')
    op.drop_table('model_promotions')
    # ### end Alembic commands ###
