"""create assistant configs table

Revision ID: 3740c95fb57a
Revises: dda8ed4848d5
Create Date: 2026-06-20 05:02:57.187285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3740c95fb57a'
down_revision: Union[str, Sequence[str], None] = 'dda8ed4848d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('rag_enabled', sa.Boolean(), nullable=False),
    sa.Column('cag_enabled', sa.Boolean(), nullable=False),
    sa.Column('tool_calling_enabled', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False
    ),

    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False
    ),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name='fk_assistant_config_assistant_id'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name='fk_assistant_config_model_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_configs_assistant_id'), 'assistant_configs', ['assistant_id'], unique=True)
    op.create_index(op.f('ix_assistant_configs_id'), 'assistant_configs', ['id'], unique=False)
    op.create_index(op.f('ix_assistant_configs_model_id'), 'assistant_configs', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assistant_configs_model_id'), table_name='assistant_configs')
    op.drop_index(op.f('ix_assistant_configs_id'), table_name='assistant_configs')
    op.drop_index(op.f('ix_assistant_configs_assistant_id'), table_name='assistant_configs')
    op.drop_table('assistant_configs')
    # ### end Alembic commands ###
