"""add tokenizer training lifecycle tables

Revision ID: 4135892e0366
Revises: 586fb52e45da
Create Date: 2026-07-08 09:45:13.554337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4135892e0366'
down_revision: Union[str, Sequence[str], None] = '586fb52e45da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenizer_implementations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('implementation_code', sa.String(length=150), nullable=False),
    sa.Column('implementation_version', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('algorithm_type', sa.String(length=100), nullable=False),
    sa.Column('trainer_class', sa.String(length=500), nullable=False),
    sa.Column('tokenizer_class', sa.String(length=500), nullable=False),
    sa.Column('training_configuration_schema_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('runtime_configuration_schema_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('capabilities_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('implementation_code', 'implementation_version', name='uq_tokenizer_implementation_code_version')
    )
    op.create_index(op.f('ix_tokenizer_implementations_algorithm_type'), 'tokenizer_implementations', ['algorithm_type'], unique=False)
    op.create_index(op.f('ix_tokenizer_implementations_id'), 'tokenizer_implementations', ['id'], unique=False)
    op.create_index(op.f('ix_tokenizer_implementations_implementation_code'), 'tokenizer_implementations', ['implementation_code'], unique=False)
    op.create_index(op.f('ix_tokenizer_implementations_is_active'), 'tokenizer_implementations', ['is_active'], unique=False)
    op.create_table('tokenizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='DRAFT', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_tokenizers_code')
    )
    op.create_index(op.f('ix_tokenizers_code'), 'tokenizers', ['code'], unique=False)
    op.create_index(op.f('ix_tokenizers_id'), 'tokenizers', ['id'], unique=False)
    op.create_index(op.f('ix_tokenizers_is_active'), 'tokenizers', ['is_active'], unique=False)
    op.create_index(op.f('ix_tokenizers_status'), 'tokenizers', ['status'], unique=False)
    op.create_table('tokenizer_training_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tokenizer_implementation_id', sa.Integer(), nullable=False),
    sa.Column('configuration_code', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tokenizer_implementation_id'], ['tokenizer_implementations.id'], name='fk_tokenizer_training_configuration_implementation_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('configuration_code', 'version', name='uq_tokenizer_training_configuration_code_version')
    )
    op.create_index(op.f('ix_tokenizer_training_configurations_configuration_code'), 'tokenizer_training_configurations', ['configuration_code'], unique=False)
    op.create_index(op.f('ix_tokenizer_training_configurations_id'), 'tokenizer_training_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_tokenizer_training_configurations_is_active'), 'tokenizer_training_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_tokenizer_training_configurations_tokenizer_implementation_id'), 'tokenizer_training_configurations', ['tokenizer_implementation_id'], unique=False)
    op.create_table('tokenizer_training_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_snapshot_id', sa.Integer(), nullable=False),
    sa.Column('tokenizer_training_configuration_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_snapshot_id'], ['dataset_snapshots.id'], name='fk_tokenizer_training_jobs_dataset_snapshot_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tokenizer_training_configuration_id'], ['tokenizer_training_configurations.id'], name='fk_tokenizer_training_jobs_training_configuration_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokenizer_training_jobs_dataset_snapshot_id'), 'tokenizer_training_jobs', ['dataset_snapshot_id'], unique=False)
    op.create_index(op.f('ix_tokenizer_training_jobs_id'), 'tokenizer_training_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_tokenizer_training_jobs_priority'), 'tokenizer_training_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_tokenizer_training_jobs_status'), 'tokenizer_training_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_tokenizer_training_jobs_tokenizer_training_configuration_id'), 'tokenizer_training_jobs', ['tokenizer_training_configuration_id'], unique=False)
    op.create_table('tokenizer_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tokenizer_id', sa.Integer(), nullable=False),
    sa.Column('tokenizer_training_job_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('vocabulary_size', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=255), nullable=False),
    sa.Column('version_metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_immutable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tokenizer_id'], ['tokenizers.id'], name='fk_tokenizer_versions_tokenizer_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tokenizer_training_job_id'], ['tokenizer_training_jobs.id'], name='fk_tokenizer_versions_training_job_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tokenizer_id', 'version', name='uq_tokenizer_versions_tokenizer_version'),
    sa.UniqueConstraint('tokenizer_training_job_id', name='uq_tokenizer_versions_training_job_id')
    )
    op.create_index(op.f('ix_tokenizer_versions_content_hash'), 'tokenizer_versions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_tokenizer_versions_id'), 'tokenizer_versions', ['id'], unique=False)
    op.create_index(op.f('ix_tokenizer_versions_is_active'), 'tokenizer_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_tokenizer_versions_status'), 'tokenizer_versions', ['status'], unique=False)
    op.create_index(op.f('ix_tokenizer_versions_tokenizer_id'), 'tokenizer_versions', ['tokenizer_id'], unique=False)
    op.create_index(op.f('ix_tokenizer_versions_tokenizer_training_job_id'), 'tokenizer_versions', ['tokenizer_training_job_id'], unique=True)
    op.create_table('tokenizer_version_artifacts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tokenizer_version_id', sa.Integer(), nullable=False),
    sa.Column('storage_instance_id', sa.Integer(), nullable=False),
    sa.Column('artifact_code', sa.String(length=255), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('storage_reference', sa.String(length=2000), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['storage_instance_id'], ['storage_instances.id'], name='fk_tokenizer_version_artifacts_storage_instance_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tokenizer_version_id'], ['tokenizer_versions.id'], name='fk_tokenizer_version_artifacts_tokenizer_version_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tokenizer_version_id', 'artifact_code', name='uq_tokenizer_version_artifacts_version_code')
    )
    op.create_index(op.f('ix_tokenizer_version_artifacts_artifact_code'), 'tokenizer_version_artifacts', ['artifact_code'], unique=False)
    op.create_index(op.f('ix_tokenizer_version_artifacts_artifact_type'), 'tokenizer_version_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_tokenizer_version_artifacts_checksum'), 'tokenizer_version_artifacts', ['checksum'], unique=False)
    op.create_index(op.f('ix_tokenizer_version_artifacts_storage_instance_id'), 'tokenizer_version_artifacts', ['storage_instance_id'], unique=False)
    op.create_index(op.f('ix_tokenizer_version_artifacts_tokenizer_version_id'), 'tokenizer_version_artifacts', ['tokenizer_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_tokenizer_version_artifacts_tokenizer_version_id'), table_name='tokenizer_version_artifacts')
    op.drop_index(op.f('ix_tokenizer_version_artifacts_storage_instance_id'), table_name='tokenizer_version_artifacts')
    op.drop_index(op.f('ix_tokenizer_version_artifacts_checksum'), table_name='tokenizer_version_artifacts')
    op.drop_index(op.f('ix_tokenizer_version_artifacts_artifact_type'), table_name='tokenizer_version_artifacts')
    op.drop_index(op.f('ix_tokenizer_version_artifacts_artifact_code'), table_name='tokenizer_version_artifacts')
    op.drop_table('tokenizer_version_artifacts')
    op.drop_index(op.f('ix_tokenizer_versions_tokenizer_training_job_id'), table_name='tokenizer_versions')
    op.drop_index(op.f('ix_tokenizer_versions_tokenizer_id'), table_name='tokenizer_versions')
    op.drop_index(op.f('ix_tokenizer_versions_status'), table_name='tokenizer_versions')
    op.drop_index(op.f('ix_tokenizer_versions_is_active'), table_name='tokenizer_versions')
    op.drop_index(op.f('ix_tokenizer_versions_id'), table_name='tokenizer_versions')
    op.drop_index(op.f('ix_tokenizer_versions_content_hash'), table_name='tokenizer_versions')
    op.drop_table('tokenizer_versions')
    op.drop_index(op.f('ix_tokenizer_training_jobs_tokenizer_training_configuration_id'), table_name='tokenizer_training_jobs')
    op.drop_index(op.f('ix_tokenizer_training_jobs_status'), table_name='tokenizer_training_jobs')
    op.drop_index(op.f('ix_tokenizer_training_jobs_priority'), table_name='tokenizer_training_jobs')
    op.drop_index(op.f('ix_tokenizer_training_jobs_id'), table_name='tokenizer_training_jobs')
    op.drop_index(op.f('ix_tokenizer_training_jobs_dataset_snapshot_id'), table_name='tokenizer_training_jobs')
    op.drop_table('tokenizer_training_jobs')
    op.drop_index(op.f('ix_tokenizer_training_configurations_tokenizer_implementation_id'), table_name='tokenizer_training_configurations')
    op.drop_index(op.f('ix_tokenizer_training_configurations_is_active'), table_name='tokenizer_training_configurations')
    op.drop_index(op.f('ix_tokenizer_training_configurations_id'), table_name='tokenizer_training_configurations')
    op.drop_index(op.f('ix_tokenizer_training_configurations_configuration_code'), table_name='tokenizer_training_configurations')
    op.drop_table('tokenizer_training_configurations')
    op.drop_index(op.f('ix_tokenizers_status'), table_name='tokenizers')
    op.drop_index(op.f('ix_tokenizers_is_active'), table_name='tokenizers')
    op.drop_index(op.f('ix_tokenizers_id'), table_name='tokenizers')
    op.drop_index(op.f('ix_tokenizers_code'), table_name='tokenizers')
    op.drop_table('tokenizers')
    op.drop_index(op.f('ix_tokenizer_implementations_is_active'), table_name='tokenizer_implementations')
    op.drop_index(op.f('ix_tokenizer_implementations_implementation_code'), table_name='tokenizer_implementations')
    op.drop_index(op.f('ix_tokenizer_implementations_id'), table_name='tokenizer_implementations')
    op.drop_index(op.f('ix_tokenizer_implementations_algorithm_type'), table_name='tokenizer_implementations')
    op.drop_table('tokenizer_implementations')
    # ### end Alembic commands ###
