"""add billing config fields to company settings

Revision ID: 4f6a6292259b
Revises: eec17e46cf49
Create Date: 2026-06-17 06:17:23.703190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6a6292259b'
down_revision: Union[str, Sequence[str], None] = 'eec17e46cf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        "company_settings",
        sa.Column(
            "tax_percentage",
            sa.Numeric(5, 2),
            server_default="18.00",
            nullable=False
        )
    )

    op.add_column(
        "company_settings",
        sa.Column(
            "invoice_prefix",
            sa.String(50),
            server_default="INV",
            nullable=False
        )
    )

    op.add_column(
        "company_settings",
        sa.Column(
            "currency_code",
            sa.String(10),
            server_default="INR",
            nullable=False
        )
    )

    op.add_column(
        "company_settings",
        sa.Column(
            "currency_symbol",
            sa.String(10),
            server_default="₹",
            nullable=False
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_settings', 'currency_symbol')
    op.drop_column('company_settings', 'currency_code')
    op.drop_column('company_settings', 'invoice_prefix')
    op.drop_column('company_settings', 'tax_percentage')
    # ### end Alembic commands ###
