"""create training providers table

Revision ID: 52c7d85947de
Revises: b18b5aa2578c
Create Date: 2026-06-22 07:12:39.775544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52c7d85947de'
down_revision: Union[str, Sequence[str], None] = 'b18b5aa2578c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),

    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_providers_code'), 'training_providers', ['code'], unique=True)
    op.create_index(op.f('ix_training_providers_id'), 'training_providers', ['id'], unique=False)
    op.create_index(op.f('ix_training_providers_provider_type'), 'training_providers', ['provider_type'], unique=False)
    
    
    # ### end Alembic commands ###


def downgrade() -> None:

    op.drop_index(
        op.f('ix_training_providers_provider_type'),
        table_name='training_providers'
    )

    op.drop_index(
        op.f('ix_training_providers_id'),
        table_name='training_providers'
    )

    op.drop_index(
        op.f('ix_training_providers_code'),
        table_name='training_providers'
    )

    op.drop_table(
        'training_providers'
    )
    # ### end Alembic commands ###
