"""create corpora tables

Revision ID: 53e37ab4e9f2
Revises: ae4db7a4fe2f
Create Date: 2026-06-23 06:36:21.606532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53e37ab4e9f2'
down_revision: Union[str, Sequence[str], None] = 'ae4db7a4fe2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),

    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_corpora_domain'), 'corpora', ['domain'], unique=False)
    op.create_index(op.f('ix_corpora_id'), 'corpora', ['id'], unique=False)
    op.create_table('corpus_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpus_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_reference', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], name='fk_corpus_source_corpus_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corpus_sources_corpus_id'), 'corpus_sources', ['corpus_id'], unique=False)
    op.create_index(op.f('ix_corpus_sources_id'), 'corpus_sources', ['id'], unique=False)
    op.create_index(op.f('ix_corpus_sources_source_type'), 'corpus_sources', ['source_type'], unique=False)
   
   
 
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    
   
    
  
    
    op.drop_index(op.f('ix_corpus_sources_source_type'), table_name='corpus_sources')
    op.drop_index(op.f('ix_corpus_sources_id'), table_name='corpus_sources')
    op.drop_index(op.f('ix_corpus_sources_corpus_id'), table_name='corpus_sources')
    op.drop_table('corpus_sources')
    op.drop_index(op.f('ix_corpora_id'), table_name='corpora')
    op.drop_index(op.f('ix_corpora_domain'), table_name='corpora')
    op.drop_table('corpora')
    # ### end Alembic commands ###
