"""create knowledge base documents table

Revision ID: 6079c1766143
Revises: 7e5285d5fb4e
Create Date: 2026-06-18 09:19:59.891332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6079c1766143'
down_revision: Union[str, Sequence[str], None] = '7e5285d5fb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], name='fk_kbd_knowledge_base_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_documents_id'), 'knowledge_base_documents', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_documents_knowledge_base_id'), 'knowledge_base_documents', ['knowledge_base_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_knowledge_base_documents_knowledge_base_id'), table_name='knowledge_base_documents')
    op.drop_index(op.f('ix_knowledge_base_documents_id'), table_name='knowledge_base_documents')
    op.drop_table('knowledge_base_documents')
    # ### end Alembic commands ###
