"""refactor models table

Revision ID: 688a8540cdb8
Revises: 95d83ce39bc4
Create Date: 2026-06-17 13:28:01.948424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '688a8540cdb8'
down_revision: Union[str, Sequence[str], None] = '95d83ce39bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.add_column('models', sa.Column('code', sa.String(length=100), nullable=False))
    op.add_column('models', sa.Column('display_name', sa.String(length=255), nullable=False))
    op.alter_column('models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('models_model_name_key', 'models', type_='unique')
    op.create_unique_constraint(None, 'models', ['code'])
    op.create_foreign_key(None, 'models', 'providers', ['provider_id'], ['id'])
    op.drop_column('models', 'provider')
    op.drop_column('models', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('models', sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_constraint(None, 'models', type_='unique')
    op.create_unique_constraint('models_model_name_key', 'models', ['model_name'])
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('models', 'display_name')
    op.drop_column('models', 'code')
    op.drop_column('models', 'provider_id')
    # ### end Alembic commands ###
