"""initial

Revision ID: 76450a702343
Revises: f27a1a140ccf
Create Date: 2026-05-23 05:11:45.583574

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '76450a702343'
down_revision: Union[str, Sequence[str], None] = 'f27a1a140ccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
