"""create assistant knowledge bases table

Revision ID: 7e5285d5fb4e
Revises: e6e82d093bb7
Create Date: 2026-06-18 08:50:54.688619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7e5285d5fb4e'
down_revision: Union[str, Sequence[str], None] = 'e6e82d093bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_knowledge_bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name='fk_akb_assistant_id'),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], name='fk_akb_knowledge_base_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assistant_id', 'knowledge_base_id', name='uq_assistant_knowledge_base')
    )
    op.create_index(op.f('ix_assistant_knowledge_bases_assistant_id'), 'assistant_knowledge_bases', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_assistant_knowledge_bases_id'), 'assistant_knowledge_bases', ['id'], unique=False)
    op.create_index(op.f('ix_assistant_knowledge_bases_knowledge_base_id'), 'assistant_knowledge_bases', ['knowledge_base_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_assistant_knowledge_bases_knowledge_base_id'), table_name='assistant_knowledge_bases')
    op.drop_index(op.f('ix_assistant_knowledge_bases_id'), table_name='assistant_knowledge_bases')
    op.drop_index(op.f('ix_assistant_knowledge_bases_assistant_id'), table_name='assistant_knowledge_bases')
    op.drop_table('assistant_knowledge_bases')
    # ### end Alembic commands ###
