"""create model deployments table

Revision ID: 85a35c8aca5b
Revises: 3740c95fb57a
Create Date: 2026-06-20 09:57:31.784115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '85a35c8aca5b'
down_revision: Union[str, Sequence[str], None] = '3740c95fb57a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('deployment_name', sa.String(length=255), nullable=False),
    sa.Column('deployment_type', sa.String(length=100), nullable=False),
    sa.Column('endpoint_url', sa.String(length=500), nullable=False),
    sa.Column('max_context_window', sa.Integer(), nullable=False),
    sa.Column('gpu_type', sa.String(length=100), nullable=True),
    sa.Column('gpu_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'),nullable=False),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),

    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.ForeignKeyConstraint(
        ['model_version_id'],
        ['model_versions.id'],
        name='fk_model_deployment_model_version_id'
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_deployments_id'), 'model_deployments', ['id'], unique=False)
    op.create_index(op.f('ix_model_deployments_model_version_id'), 'model_deployments', ['model_version_id'], unique=False)
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_model_deployments_model_version_id'), table_name='model_deployments')
    op.drop_index(op.f('ix_model_deployments_id'), table_name='model_deployments')
    op.drop_table('model_deployments')
    # ### end Alembic commands ###
