"""add multilingual document fields

Revision ID: 970427ce953c
Revises: 8ab07c199057
Create Date: 2026-05-15 08:35:05.234005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '970427ce953c'
down_revision: Union[str, Sequence[str], None] = '8ab07c199057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_content', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('language', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('is_translated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_translated')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'original_content')
    # ### end Alembic commands ###
