"""add plan references to subscriptions

Revision ID: a2452f670199
Revises: 134f0d0dac8f
Create Date: 2026-06-12 05:21:31.257985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2452f670199'
down_revision: Union[str, Sequence[str], None] = '134f0d0dac8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan_id', sa.BigInteger(), nullable=True))
    op.add_column('subscriptions', sa.Column('plan_version_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        "fk_subscriptions_plan_id",
        "subscriptions",
        "plans",
        ["plan_id"],
        ["id"]
    )

    op.create_foreign_key(
        "fk_subscriptions_plan_version_id",
        "subscriptions",
        "plan_versions",
        ["plan_version_id"],
        ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_subscriptions_plan_version_id",
        "subscriptions",
        type_="foreignkey"
    )

    op.drop_constraint(
        "fk_subscriptions_plan_id",
        "subscriptions",
        type_="foreignkey"
    )
    op.drop_column('subscriptions', 'plan_version_id')
    op.drop_column('subscriptions', 'plan_id')
    # ### end Alembic commands ###
