"""conversation architecture

Revision ID: a25c3c680800
Revises: 970427ce953c
Create Date: 2026-05-19 09:22:39.044479

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a25c3c680800'
down_revision: Union[str, Sequence[str], None] = '970427ce953c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
