"""invoice production fields

Revision ID: a8a7151213bb
Revises: 27825b1c7022
Create Date: 2026-06-09 08:57:05.686930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8a7151213bb'
down_revision: Union[str, Sequence[str], None] = '27825b1c7022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_type', sa.String(length=50), nullable=False))
    op.add_column('invoices', sa.Column('subtotal', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.Numeric(precision=18, scale=6), nullable=False))
    op.add_column('invoices', sa.Column('payment_provider', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('payment_reference', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('auto_renew', sa.Boolean(), nullable=False))
    op.add_column('invoices', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('notes', sa.String(length=500), nullable=True))
    op.add_column('invoices', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('invoices', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('invoices', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint('invoices_invoice_number_key', 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_foreign_key(None, 'invoices', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_unique_constraint('invoices_invoice_number_key', 'invoices', ['invoice_number'])
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('invoices', 'amount',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('invoices', 'updated_at')
    op.drop_column('invoices', 'is_active')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'paid_at')
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'auto_renew')
    op.drop_column('invoices', 'payment_reference')
    op.drop_column('invoices', 'payment_provider')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoices', 'invoice_type')
    op.drop_column('invoices', 'subscription_id')
    # ### end Alembic commands ###
