"""create model artifacts table

Revision ID: abd5baa2ae71
Revises: 0124b722b3b9
Create Date: 2026-06-20 11:47:05.357081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'abd5baa2ae71'
down_revision: Union[str, Sequence[str], None] = '0124b722b3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_job_id', sa.Integer(), nullable=False),
    sa.Column('artifact_name', sa.String(length=255), nullable=False),
    sa.Column('artifact_path', sa.String(length=1000), nullable=False),
    sa.Column('artifact_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=255), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),

    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.ForeignKeyConstraint(['training_job_id'], ['training_jobs.id'], name='fk_model_artifact_training_job_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_artifacts_id'), 'model_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_model_artifacts_training_job_id'), 'model_artifacts', ['training_job_id'], unique=False)
    op.create_index(
        'ix_model_artifacts_artifact_type',
        'model_artifacts',
        ['artifact_type'],
        unique=False
    )
    
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        'ix_model_artifacts_artifact_type',
        table_name='model_artifacts'
    )
   
    
    op.drop_index(op.f('ix_model_artifacts_training_job_id'), table_name='model_artifacts')
    op.drop_index(op.f('ix_model_artifacts_id'), table_name='model_artifacts')
    op.drop_table('model_artifacts')
    # ### end Alembic commands ###
