"""link documents to knowledge base documents

Revision ID: ae2009452679
Revises: 6079c1766143
Create Date: 2026-06-18 09:36:48.531285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ae2009452679'
down_revision: Union[str, Sequence[str], None] = '6079c1766143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('knowledge_base_document_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_documents_knowledge_base_document_id'), 'documents', ['knowledge_base_document_id'], unique=False)
    op.create_foreign_key('fk_document_kbd_id', 'documents', 'knowledge_base_documents', ['knowledge_base_document_id'], ['id'])
  
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_constraint('fk_document_kbd_id', 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_knowledge_base_document_id'), table_name='documents')
    op.drop_column('documents', 'knowledge_base_document_id')
    # ### end Alembic commands ###
