"""create model releases table

Revision ID: b18b5aa2578c
Revises: 2c5b12e13a6f
Create Date: 2026-06-20 12:53:06.385982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b18b5aa2578c'
down_revision: Union[str, Sequence[str], None] = '2c5b12e13a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('release_version', sa.String(length=100), nullable=False),
    sa.Column('release_name', sa.String(length=255), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column(
        'release_status',
        sa.String(length=50),
        server_default=sa.text("'draft'"),
        nullable=False
    ),

    sa.Column(
        'created_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),

    sa.Column(
        'updated_at',
        sa.DateTime(),
        server_default=sa.text('now()'),
        nullable=False
    ),
    sa.ForeignKeyConstraint(['promotion_id'], ['model_promotions.id'], name='fk_model_release_promotion_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_releases_id'), 'model_releases', ['id'], unique=False)
    op.create_index(op.f('ix_model_releases_promotion_id'), 'model_releases', ['promotion_id'], unique=False)
    op.create_index(
        'ix_model_releases_status',
        'model_releases',
        ['release_status'],
        unique=False
    )
   
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_model_releases_status',
        table_name='model_releases'
    )
   
   
    op.drop_index(op.f('ix_model_releases_promotion_id'), table_name='model_releases')
    op.drop_index(op.f('ix_model_releases_id'), table_name='model_releases')
    op.drop_table('model_releases')
    # ### end Alembic commands ###
