"""initial tables

Revision ID: b7fb52c07980
Revises: 
Create Date: 2026-05-08 11:15:15.102418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7fb52c07980'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    #op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    #op.drop_table('conversations')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('conversations',
   # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    #sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    #sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    #sa.Column('query', sa.TEXT(), autoincrement=False, nullable=True),
    #sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    #sa.Column('model_used', sa.VARCHAR(), autoincrement=False, nullable=True),
    #sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    #sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    #)
    #op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    #op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    # ### end Alembic commands ###
    pass
