"""create assistant model versions table

Revision ID: c3e4815366de
Revises: ad2683a19e0d
Create Date: 2026-06-18 07:32:15.892178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3e4815366de'
down_revision: Union[str, Sequence[str], None] = 'ad2683a19e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assistant_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name='fk_amv_assistant_id'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name='fk_amv_model_version_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assistant_id', 'model_version_id', name='uq_assistant_model_version')
    )
    op.create_index(op.f('ix_assistant_model_versions_assistant_id'), 'assistant_model_versions', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_assistant_model_versions_id'), 'assistant_model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_assistant_model_versions_model_version_id'), 'assistant_model_versions', ['model_version_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_assistant_model_versions_model_version_id'), table_name='assistant_model_versions')
    op.drop_index(op.f('ix_assistant_model_versions_id'), table_name='assistant_model_versions')
    op.drop_index(op.f('ix_assistant_model_versions_assistant_id'), table_name='assistant_model_versions')
    op.drop_table('assistant_model_versions')
    # ### end Alembic commands ###
