"""create assistants tables

Revision ID: dda8ed4848d5
Revises: be4c89ad1e6a
Create Date: 2026-06-19 07:24:58.848713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dda8ed4848d5'
down_revision: Union[str, Sequence[str], None] = 'be4c89ad1e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_akb_assistant_kb', 'assistant_knowledge_bases', ['assistant_id', 'knowledge_base_id'], unique=False)
    op.alter_column('assistants', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('document_jobs', 'knowledge_base_document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('models', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('models', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('document_jobs', 'knowledge_base_document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('assistants', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index('ix_akb_assistant_kb', table_name='assistant_knowledge_bases')
    # ### end Alembic commands ###
