"""create connector registry tables

Revision ID: df650da5effa
Revises: c3a14be429a6
Create Date: 2026-06-24 06:50:17.422833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df650da5effa'
down_revision: Union[str, Sequence[str], None] = 'c3a14be429a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_types_code'), 'connector_types', ['code'], unique=True)
    op.create_table('connector_implementations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_type_id', sa.Integer(), nullable=False),
    sa.Column('implementation_code', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('configuration_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_type_id'], ['connector_types.id'], name='fk_connector_impl_type_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('implementation_code', 'version', name='uq_connector_impl_version')
    )
    op.create_index(op.f('ix_connector_implementations_connector_type_id'), 'connector_implementations', ['connector_type_id'], unique=False)
    op.create_index(op.f('ix_connector_implementations_implementation_code'), 'connector_implementations', ['implementation_code'], unique=False)
    op.create_index(op.f('ix_connector_implementations_status'), 'connector_implementations', ['status'], unique=False)
    op.create_table('connector_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_implementation_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instance_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_implementation_id'], ['connector_implementations.id'], name='fk_connector_instance_impl_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connector_instances_connector_implementation_id'), 'connector_instances', ['connector_implementation_id'], unique=False)
   
    op.create_index(op.f('ix_connector_instances_instance_code'), 'connector_instances', ['instance_code'], unique=True)
    op.create_index(op.f('ix_connector_instances_organization_id'), 'connector_instances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_connector_instances_status'), 'connector_instances', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  
    op.drop_index(op.f('ix_connector_instances_status'), table_name='connector_instances')
    op.drop_index(op.f('ix_connector_instances_organization_id'), table_name='connector_instances')
    op.drop_index(op.f('ix_connector_instances_instance_code'), table_name='connector_instances')
    
    op.drop_index(op.f('ix_connector_instances_connector_implementation_id'), table_name='connector_instances')
    op.drop_table('connector_instances')
    op.drop_index(op.f('ix_connector_implementations_status'), table_name='connector_implementations')
    op.drop_index(op.f('ix_connector_implementations_implementation_code'), table_name='connector_implementations')
    op.drop_index(op.f('ix_connector_implementations_connector_type_id'), table_name='connector_implementations')
    op.drop_table('connector_implementations')
    op.drop_index(op.f('ix_connector_types_code'), table_name='connector_types')
    op.drop_table('connector_types')
    # ### end Alembic commands ###
