"""add training job progress columns

Revision ID: e0140ed569d5
Revises: d0b08d9a5569
Create Date: 2026-07-11 10:56:38.340904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0140ed569d5'
down_revision: Union[str, Sequence[str], None] = 'd0b08d9a5569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'training_jobs',
        sa.Column('queued_at', sa.DateTime(), nullable=True)
    )

    op.add_column(
        'training_jobs',
        sa.Column('failed_at', sa.DateTime(), nullable=True)
    )

    op.add_column(
        'training_jobs',
        sa.Column('failure_reason', sa.String(length=4000), nullable=True)
    )

    op.add_column(
        'training_jobs',
        sa.Column('current_epoch', sa.Integer(), server_default='0', nullable=False)
    )
 
    op.add_column(
        'training_jobs',
        sa.Column('current_step', sa.Integer(), server_default='0', nullable=False)
    )

    op.add_column(
        'training_jobs',
        sa.Column('global_step', sa.Integer(), server_default='0', nullable=False)
    )

    op.add_column(
        'training_jobs',
        sa.Column('processed_samples', sa.Integer(), server_default='0', nullable=False)
    )

    op.add_column(
        'training_jobs',
        sa.Column('processed_tokens', sa.Integer(), server_default='0', nullable=False)
    )

    op.add_column(
        'training_jobs',
        sa.Column('current_loss', sa.Numeric(precision=18, scale=8), nullable=True)
    )

    op.add_column(
        'training_jobs',
        sa.Column('learning_rate', sa.Numeric(precision=18, scale=12), nullable=True)
    )

    op.add_column(
        'training_jobs',
        sa.Column('last_checkpoint_path', sa.String(length=1000), nullable=True)
    )

    op.add_column(
        'training_jobs',
        sa.Column('last_checkpoint_at', sa.DateTime(), nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        'training_jobs',
        'last_checkpoint_at'
    )

    op.drop_column(
        'training_jobs',
        'last_checkpoint_path'
    )

    op.drop_column(
        'training_jobs',
        'learning_rate'
    )

    op.drop_column(
        'training_jobs',
        'current_loss'
    )

    op.drop_column(
        'training_jobs',
        'processed_tokens'
    )

    op.drop_column(
        'training_jobs',
        'processed_samples'
    )

    op.drop_column(
        'training_jobs',
        'global_step'
    )

    op.drop_column(
        'training_jobs',
        'current_step'
    )

    op.drop_column(
        'training_jobs',
        'current_epoch'
    )

    op.drop_column(
        'training_jobs',
        'failure_reason'
    )

    op.drop_column(
        'training_jobs',
        'failed_at'
    )

    op.drop_column(
        'training_jobs',
        'queued_at'
    )