"""add user name field

Revision ID: e1093cf1b80f
Revises: 76450a702343
Create Date: 2026-05-28 12:02:24.522414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1093cf1b80f'
down_revision: Union[str, Sequence[str], None] = '76450a702343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(

        "users",

        sa.Column(
            "name",
            sa.String(),
            nullable=True
        )
    )

    op.execute(
        """
        UPDATE users
        SET name = 'Unknown User'
        WHERE name IS NULL
        """
    )

    op.alter_column(

        "users",

        "name",

        nullable=False
    )




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###

