"""create billing tables

Revision ID: e942f203cec5
Revises: 9f403f302dd8
Create Date: 2026-06-06 06:33:20.785942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e942f203cec5'
down_revision: Union[str, Sequence[str], None] = '9f403f302dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS payments CASCADE;")
    op.execute("DROP TABLE IF EXISTS invoices CASCADE;")
    op.execute("DROP TABLE IF EXISTS usage_limits CASCADE;")
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['id'])
    op.alter_column('wallet_transactions', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wallet_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=False)
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=False)
    op.create_foreign_key(None, 'wallet_transactions', 'wallets', ['wallet_id'], ['id'])
    op.alter_column('wallets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.alter_column('wallets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'wallet_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.alter_column('wallet_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=18, scale=6),
               nullable=True)
    op.alter_column('wallet_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('wallet_transactions', 'wallet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.create_table('usage_limits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('daily_token_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('monthly_token_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('request_limit', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='usage_limits_pkey')
    )
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('billing_period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('billing_period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='invoices_pkey')
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    # ### end Alembic commands ###
