class PipelineArtifactRelation:

    DERIVED_FROM = "DERIVED_FROM"

    EXTRACTED_FROM = "EXTRACTED_FROM"

    OCR_DERIVED_FROM = "OCR_DERIVED_FROM"

    NLP_DERIVED_FROM = "NLP_DERIVED_FROM"

    CHUNKED_FROM = "CHUNKED_FROM"

    TOKENIZED_FROM = "TOKENIZED_FROM"

    MATERIALIZED_FROM = "MATERIALIZED_FROM"

    AGGREGATED_FROM = "AGGREGATED_FROM"