class PipelineArtifactType:

    SOURCE_REFERENCE = "SOURCE_REFERENCE"

    PARSED_DOCUMENT = "PARSED_DOCUMENT"

    OCR_DOCUMENT = "OCR_DOCUMENT"

    NLP_DOCUMENT = "NLP_DOCUMENT"

    DOCUMENT_CHUNK = "DOCUMENT_CHUNK"

    TOKENIZED_CHUNK = "TOKENIZED_CHUNK"

    DATASET_RECORD = "DATASET_RECORD"

    TRAINING_MATERIALIZATION = (
        "TRAINING_MATERIALIZATION"
    )